"""add draft_prompt_version

Revision ID: 32ca8c75488c
Revises: 5996a824999c
Create Date: 2026-05-15 14:54:15.582286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ca8c75488c'
down_revision: Union[str, None] = '5996a824999c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('draft_prompt_version', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'draft_prompt_version')
    # ### end Alembic commands ###
