"""add draft columns to emails

Revision ID: 5996a824999c
Revises: 07e5a3a109d2
Create Date: 2026-05-15 14:46:44.014715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5996a824999c'
down_revision: Union[str, None] = '07e5a3a109d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default='false' fills existing rows before applying NOT NULL constraint.
    # Without this, PostgreSQL rejects the migration because existing rows would be NULL.
    op.add_column('emails', sa.Column('draft_generated', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('emails', sa.Column('gmail_draft_id', sa.String(length=128), nullable=True))
    op.add_column('emails', sa.Column('draft_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'draft_generated_at')
    op.drop_column('emails', 'gmail_draft_id')
    op.drop_column('emails', 'draft_generated')
    # ### end Alembic commands ###
