"""add draft_edited_before_send

Revision ID: 6c38f4b59a6e
Revises: 32ca8c75488c
Create Date: 2026-05-15 14:57:05.587038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c38f4b59a6e'
down_revision: Union[str, None] = '32ca8c75488c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('draft_edited_before_send', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'draft_edited_before_send')
    # ### end Alembic commands ###
